### ISSUE TITLE
Please add unicode as dependency on gemspec

### ISSUE THREAD

**Issue by poudelprakash** [hashwin/scylla#5]
Guys, your gem has dependency on unicode gem. Please add that to gemspec.
### Before I had unicode installed:

``` ruby
>> require 'scylla/generator'
LoadError: cannot load such file -- unicode
    from /home/prakash/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/prakash/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/prakash/.rvm/gems/ruby-2.3.0/gems/scylla-1.0.7/lib/scylla/generator.rb:4:in `<top (required)>'
    from /home/prakash/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    from /home/prakash/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    from /home/prakash/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from (irb):1
    from /home/prakash/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```
### after I installed unicode manually:

``` ruby
>> require 'scylla/generator'
=> true
```

**Comment by coding-bunny** [comment]
Is this gem still maintained?

**Comment by hashwin** [comment]
Not actively maintained, but I'll take pull requests.

**Comment by coding-bunny** [comment]
then this can be closed now ;)
Although a version bump is in order I think for the change

**Comment by hashwin** [comment]
Done
